
# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = yes, please :)

    # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    # Fluid & Bouncy curves
    bezier = fluid,          0.08,  0.95,  0.2,  1.12
    bezier = md3_decel,      0.12,  0.8,   0.2,  1
    bezier = md3_accel,      0.25,  0.05,  0.4,  0.2
    bezier = md3_bounce,     0.12,  0.9,   0.2,  1.08

    # Animation configs
    animation = global,        1,     10,    default
    animation = border,        1,     10,    default
    animation = borderangle,   1,     8,     default

    animation = windows,       1,     7,     fluid
    animation = windowsIn,     1,     6,     md3_decel, popin 10%
    animation = windowsOut,    1,     6,     md3_accel, popin 10%
    animation = windowsMove,   1,     7,     fluid,

    animation = fadeIn,        1,     7,     default
    animation = fadeOut,       1,     7,     default
    animation = fade,          1,     7,     default

    animation = workspaces,    1,     7,     fluid, slidevert
    animation = workspacesIn,  1,     7,     fluid, slidevert
    animation = workspacesOut, 1,     7,     fluid, slidevert

    animation = specialWorkspace, 1,  6,     md3_bounce, slidevert

    animation = layers,        1,     6,     md3_decel, fluid
    animation = layersIn,      1,     6,     md3_decel, slide
    animation = layersOut,     1,     6,     md3_accel, slide
}
