

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = wl-paste --type text --watch cliphist store & wl-paste --type image --watch cliphist store & waybar & hyprpaper & firefox
exec-once = hyprpm reload -n
exec-once = wl-paste --type text --watch cliphist store & wl-paste --type image --watch cliphist store & waybar & hypridle & swaync & awww-daemon & swayosd-server & snappy-switcher --daemon
exec-once = ~/.config/hypr/Scripts/battery_notify.sh
