# plugin {
#     hyprexpo {
#         columns = 3
#         gap_size = 10
#         bg_col = $background
#         workspace_method = center current
#
#         gesture_distance = 300
#     }
# }


plugin:hyprglass {
    default_theme = dark
    default_preset = liquid_glass

    dark:brightness = 0.88
    dark:contrast = 0.95
    dark:vibrancy = 0.25

    preset = name:liquid_glass, glass_opacity:0.85, blur_strength:2.5, blur_iterations:3
    preset = name:liquid_glass, refraction_strength:0.85, edge_thickness:0.08
    preset = name:liquid_glass, chromatic_aberration:0.8, fresnel_strength:0.9, specular_strength:0.95
    preset = name:liquid_glass, lens_distortion:0.9, adaptive_boost:0.1, vibrancy_darkness:1
    preset = name:liquid_glass:dark, tint_color:$primary_hex, brightness:1, contrast:1.7, saturation:1, vibrancy:0.8

    layers {
        enabled = 1
        namespaces = waybar, swaync, wlogout, rofi
        exclude_namespaces = debug-panel
        preset = liquid_glass

        namespace_mask_thresholds = waybar=0.1, swaync=0.05
    }
}
