

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = zen-browser
$discord = vesktop
$neovim = $terminal -e nvim
$yazi = $terminal -e yazi
$music = youtube-music
