
#####################
###   LAYERRULE   ###
#####################

layerrule = blur on, match:namespace wlogout
layerrule = blur on, animation slide left, match:namespace rofi
layerrule = blur on, match:namespace snappy-switcher

layerrule = blur on, animation slide top, dim_around on, match:namespace swaync-control-center
layerrule = blur off, dim_around on, match:namespace swaync-notification-window

layerrule = blur on, ignore_alpha 0.5, match:class swayosd
layerrule = blur on, match:class waybar

#####################
###  WINDOWRULE   ###
#####################

windowrule = float 1, match:class ^([Rr]ofi)$
windowrule = pin 1, match:class ^([Rr]ofi)$
windowrule = center 1, match:class ^([Rr]ofi)$

# See https://wiki.hypr.land/Configurin/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
  name = discord-special-magic

  match:class = ^(vesktop)$

  workspace = special:magic
  float = true
  size = 1435 776
  move = 236 236
}

# Fix some dragging issues with XWayland
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

xwayland {
  force_zero_scaling = true
}
# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

