
$image = /home/bimbok/arch/walls/37.jpg
$background = rgba(191114ff)

$image = /home/bimbok/arch/walls/37.jpg
$error = rgba(ffb4abff)

$image = /home/bimbok/arch/walls/37.jpg
$error_container = rgba(93000aff)

$image = /home/bimbok/arch/walls/37.jpg
$inverse_on_surface = rgba(372e31ff)

$image = /home/bimbok/arch/walls/37.jpg
$inverse_primary = rgba(8a4a66ff)

$image = /home/bimbok/arch/walls/37.jpg
$inverse_surface = rgba(eedfe2ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_background = rgba(eedfe2ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_error = rgba(690005ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_error_container = rgba(ffdad6ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_primary = rgba(531d37ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_primary_container = rgba(ffd8e5ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_primary_fixed = rgba(390722ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_primary_fixed_variant = rgba(6e334eff)

$image = /home/bimbok/arch/walls/37.jpg
$on_secondary = rgba(412a33ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_secondary_container = rgba(fed9e5ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_secondary_fixed = rgba(2a151eff)

$image = /home/bimbok/arch/walls/37.jpg
$on_secondary_fixed_variant = rgba(593f49ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_surface = rgba(eedfe2ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_surface_variant = rgba(d5c2c7ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_tertiary = rgba(49280eff)

$image = /home/bimbok/arch/walls/37.jpg
$on_tertiary_container = rgba(ffdcc5ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_tertiary_fixed = rgba(301400ff)

$image = /home/bimbok/arch/walls/37.jpg
$on_tertiary_fixed_variant = rgba(633e23ff)

$image = /home/bimbok/arch/walls/37.jpg
$outline = rgba(9d8c91ff)

$image = /home/bimbok/arch/walls/37.jpg
$outline_variant = rgba(504348ff)

$image = /home/bimbok/arch/walls/37.jpg
$primary = rgba(ffb0cfff)

$image = /home/bimbok/arch/walls/37.jpg
$primary_container = rgba(6e334eff)

$image = /home/bimbok/arch/walls/37.jpg
$primary_fixed = rgba(ffd8e5ff)

$image = /home/bimbok/arch/walls/37.jpg
$primary_fixed_dim = rgba(ffb0cfff)

$image = /home/bimbok/arch/walls/37.jpg
$scrim = rgba(000000ff)

$image = /home/bimbok/arch/walls/37.jpg
$secondary = rgba(e1bdc9ff)

$image = /home/bimbok/arch/walls/37.jpg
$secondary_container = rgba(593f49ff)

$image = /home/bimbok/arch/walls/37.jpg
$secondary_fixed = rgba(fed9e5ff)

$image = /home/bimbok/arch/walls/37.jpg
$secondary_fixed_dim = rgba(e1bdc9ff)

$image = /home/bimbok/arch/walls/37.jpg
$shadow = rgba(000000ff)

$image = /home/bimbok/arch/walls/37.jpg
$source_color = rgba(d63e8eff)

$image = /home/bimbok/arch/walls/37.jpg
$surface = rgba(191114ff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_bright = rgba(40373aff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_container = rgba(261d20ff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_container_high = rgba(30282bff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_container_highest = rgba(3c3235ff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_container_low = rgba(21191cff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_container_lowest = rgba(130c0fff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_dim = rgba(191114ff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_tint = rgba(ffb0cfff)

$image = /home/bimbok/arch/walls/37.jpg
$surface_variant = rgba(504348ff)

$image = /home/bimbok/arch/walls/37.jpg
$tertiary = rgba(f1bb97ff)

$image = /home/bimbok/arch/walls/37.jpg
$tertiary_container = rgba(633e23ff)

$image = /home/bimbok/arch/walls/37.jpg
$tertiary_fixed = rgba(ffdcc5ff)

$image = /home/bimbok/arch/walls/37.jpg
$tertiary_fixed_dim = rgba(f1bb97ff)

