$hyprlockDir = $HOME/.config/hypr/hyprlock
$dynamicColorsDir = $hyprlockDir/colors_dynamic

source = $dynamicColorsDir/colors.conf
source = $hyprlockDir/colors.conf
source = $hyprlockDir/layouts/layout.conf
