#####################
###  INRODUCTION  ###
#####################
source = ~/.config/hypr/Modules/intro.conf

#####################
###  MATUGEN      ###
#####################
source = ~/.config/hypr/Modules/colors.conf


#####################
###  CURSOR       ###
#####################
source = ~/.config/hypr/Modules/cursor.conf

################
### MONITORS ###
################
source = ~/.config/hypr/Modules/monitor.conf

###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/Modules/programs.conf

#################
### AUTOSTART ###
#################
source = ~/.config/hypr/Modules/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/Modules/enviornments.conf

###################
### PERMISSIONS ###
###################
source = ~/.config/hypr/Modules/permissions.conf

#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/Modules/appearance.conf

#####################
###  ANIMATIONS   ###
#####################
source = ~/.config/hypr/Modules/animations.conf

#####################
###  LAYOUT       ###
#####################
source = ~/.config/hypr/Modules/layout.conf

#####################
###  MISC         ###
#####################
source = ~/.config/hypr/Modules/misc.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/Modules/input.conf

###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/Modules/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/Modules/windowrules.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/Modules/plugins.conf
